---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Update apt cache for Debian
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == 'Debian'
  roles:
  - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
